export const Questions = [
    {
      prompt: "What is the latest version of JavaScript?",
      optionA: "ES5",
      optionB: "ES6",
      optionC: "ES7",
      optionD: "ES8",
      answer: "optionD",
    },
    {
      prompt: "Which of the following is not a JavaScript data type?",
      optionA: "string",
      optionB: "number",
      optionC: "boolean",
      optionD: "float",
      answer: "optionD",
    },
    {
      prompt: "What is the output of the following code: console.log(5 + '5')?",
      optionA: "10",
      optionB: "55",
      optionC: "undefined",
      optionD: "NaN",
      answer: "optionB",
    },
    {
      prompt: "What does the keyword 'this' refer to in JavaScript?",
      optionA: "The current function",
      optionB: "The global object",
      optionC: "The object that the function is a method of",
      optionD: "The parent object of the current object",
      answer: "optionC",
    },
    {
      prompt: "What is the difference between '==' and '===' in JavaScript?",
      optionA: "'==' compares values and '===' compares both valuesand types",
      optionB: "'===' compares values and '==' compares both values and types",
      optionC: "'==' compares values and '===' compares types",
      optionD: "There is no difference between '==' and '==='",
      answer: "optionA",
    },
    {
      prompt: "What is the purpose of a closure in JavaScript?",
      optionA: "To protect variables from being modified",
      optionB: "To hide variables and methods from being accessed",
      optionC: "To create private variables and methods",
      optionD: "All of the above",
      answer: "optionD",
    },
    {
      prompt: "What is the difference between 'var', 'let', and 'const' in JavaScript?",
      optionA: "'var' is for global variables, 'let' and 'const' are for block-scoped variables",
      optionB: "'var' is for block-scoped variables, 'let' and 'const' are for global variables",
      optionC: "'let' and 'const' are for global variables, 'var' is for block-scoped variables",
      optionD: "There is no difference between 'var', 'let', and 'const'",
      answer: "optionA",
    },
    {
      prompt: "Which of the following is not a higher-order function in JavaScript?",
      optionA: "map()",
      optionB: "filter()",
      optionC: "forEach()",
      optionD: "parseInt()",
      answer: "optionD",
    },
    {
      prompt: "What is the purpose of the 'use strict' directive in JavaScript?",
      optionA: "To enable strict mode, which enforces stricter parsing and error handling",
      optionB: "To disable strict mode, which allows for more lenient parsing and error handling",
      optionC: "To enable strict mode, which allows for more lenient parsing and error handling",
      optionD: "To disable strict mode, which enforces stricter parsing and error handling",
      answer: "optionA",
    },
    {
      prompt: "What is the difference between a synchronous and asynchronous function in JavaScript?",
      optionA: "A synchronous function blocks the main thread, while an asynchronous function does not",
      optionB: "A synchronous function does not block the main thread, while an asynchronous function does",
      optionC: "There is no difference between a synchronous and asynchronous function",
      optionD: "A synchronous function returns a value immediately, while an asynchronous function returns a value later",
      answer: "optionA",
    },
    {
      prompt: "What is a promise in JavaScript?",
      optionA: "A value that may not yet be available, but will be at some point in the future",
      optionB: "A function that returns a value immediately",
      optionC: "An object that represents the eventualcompletion (or failure) of an asynchronous operation and its resulting value",
      optionD: "A method that executes a block of code when a certain event occurs",
      answer: "optionC",
    },
    {
      prompt: "What is Node.js?",
      optionA: "A web browser",
      optionB: "A server-side runtime environment for JavaScript",
      optionC: "A client-side runtime environment for JavaScript",
      optionD: "A database management system",
      answer: "optionB",
    },
    {
      prompt: "What is NPM?",
      optionA: "A package manager for Node.js",
      optionB: "A web development framework",
      optionC: "A server-side runtime environment for JavaScript",
      optionD: "A client-side runtime environment for JavaScript",
      answer: "optionA",
    },
    {
      prompt: "Which of the following is not a popular Node.js web framework?",
      optionA: "Express",
      optionB: "Meteor",
      optionC: "Next.js",
      optionD: "Hapi",
      answer: "optionC",
    },
    {
      prompt: "What is a middleware in Node.js?",
      optionA: "A function that can access the request and response objects and modify them",
      optionB: "A function that returns a promise",
      optionC: "A function that executes a block of code when a certain event occurs",
      optionD: "A function that creates and manages a database connection",
      answer: "optionA",
    },
    {
      prompt: "What is the purpose of the 'body-parser' middleware in Node.js?",
      optionA: "To parse the request body and make it available in the request object",
      optionB: "To parse the response body and make it available in the response object",
      optionC: "To handle CORS (Cross-Origin Resource Sharing) requests",
      optionD: "To handle authentication and authorization",
      answer: "optionA",
    },
    {
      prompt: "What is MongoDB?",
      optionA: "A relational database management system",
      optionB: "A NoSQL document database",
      optionC: "A server-side runtime environment for JavaScript",
      optionD: "A client-side runtime environment for JavaScript",
      answer: "optionB",
    },
    {
      prompt: "What is Mongoose?",
      optionA: "A web development framework",
      optionB: "A server-side runtime environment for JavaScript",
      optionC: "An object data modeling (ODM) library for MongoDB",
      optionD: "A client-side runtime environment for JavaScript",
      answer: "optionC",
    },
    {
      prompt: "What is Express?",
      optionA: "A web server",
      optionB: "A web development framework for Node.js",
      optionC: "A client-side runtime environment for JavaScript",
      optionD: "A server-side runtime environment for JavaScript",
      answer: "optionB",
    },
    {
      prompt: "What is React?",
      optionA: "A server-side runtime environment for JavaScript",
      optionB: "A client-side runtime environment for JavaScript",
      optionC: "A web development framework for Node.js",
      optionD: "A JavaScript library for building user interfaces",
      answer: "optionD",
    },
    {
      prompt: "What is JSX?",
      optionA: "A server-side scripting language",
      optionB: "A client-side scripting language",
      optionC: "A syntax extension for JavaScript that allows XML-like code to be written in JavaScript",
      optionD: "An object-oriented programming language",
      answer: "optionC",
    },
    {
      prompt: "What is the difference between props and state in React?",
      optionA: "Props are immutable and state is mutable",
      optionB: "State is immutable and props is mutable",
      optionC: "There is no difference between props and state",
      optionD: "Props are used to pass data from a parent component to a child component, while state is used to manage data within a component",
      answer: "optionD",
    },
    {
      prompt: "What is a component in React?",
      optionA: "A function or class that returns HTML-like code",
      optionB: "A function orclass that represents a reusable piece of UI",
      optionC: "A function or class that manages data within a component",
      optionD: "A function or class that creates and manages a database connection",
      answer: "optionB",
    },
    {
      prompt: "What is Redux?",
      optionA: "A web development framework",
      optionB: "A server-side runtime environment for JavaScript",
      optionC: "A state management library for React",
      optionD: "A client-side runtime environment for JavaScript",
      answer: "optionC",
    },
    {
      prompt: "What is a reducer in Redux?",
      optionA: "A function that returns the new state based on the previous state and an action",
      optionB: "A function that creates a new Redux store",
      optionC: "A function that updates the state of a component",
      optionD: "A function that creates and manages a database connection",
      answer: "optionA",
    },
    {
      prompt: "What is a saga in Redux?",
      optionA: "A function that handles asynchronous actions in Redux",
      optionB: "A function that handles synchronous actions in Redux",
      optionC: "A function that creates a new Redux store",
      optionD: "A function that updates the state of a component",
      answer: "optionA",
    },
    {
      prompt: "What is a Higher Order Component (HOC) in React?",
      optionA: "A function that returns a new component with added functionality",
      optionB: "A component that is rendered higher up in the component tree",
      optionC: "A component that is passed as a prop to another component",
      optionD: "A component that is created using the 'class' syntax",
      answer: "optionA",
    },
    {
      prompt: "What is CSS?",
      optionA: "A programming language used to create dynamic web pages",
      optionB: "A scripting language used to create dynamic web pages",
      optionC: "A markup language used to create the structure of web pages",
      optionD: "A styling language used to change the appearance of web pages",
      answer: "optionD",
    },
    {
      prompt: "What is the box model in CSS?",
      optionA: "A model used to create 3D shapes in CSS",
      optionB: "A model used to create responsive layouts in CSS",
      optionC: "A model used to calculate the size and position of elements in CSS",
      optionD: "A model used to create animations in CSS",
      answer: "optionC",
    },
    {
      prompt: "What is Flexbox in CSS?",
      optionA: "A layout mode used for positioning and aligning elements in a one-dimensional space",
      optionB: "A layout mode used for positioning and aligning elements in a two-dimensional space",
      optionC: "A layout mode used for creating responsive designs",
      optionD: "A layout mode used for creating animations",
      answer: "optionA",
    },
    {
      prompt: "What is Grid in CSS?",
      optionA: "A layout mode used for positioning and aligning elements in a one-dimensional space",
      optionB: "A layout mode used for positioning and aligning elements in a two-dimensional space",
      optionC: "A layout mode used for creating responsive designs",
      optionD: "A layout mode used for creating animations",
      answer: "optionB",
    },
    {
      prompt: "What is the difference between 'px', 'em', and 'rem' in CSS?",
      optionA: "'px' is a fixed unit, 'em' is relative to the font size of the element, and 'rem' is relative to the font size of the root element",
      optionB: "'em' is a fixed unit, 'px' is relative to the font size of the element, and 'rem' is relative to the font size of the root element",
      optionC: "'rem' is a fixed unit, 'px' is relative to the font size of the element, and 'em' is relative to the font size of the root element",
      optionD: "There is no difference between 'px', 'em', and 'rem'",
      answer: "optionA",
    },
    {
      prompt: "What is the difference between 'margin' and 'padding' in CSS?",
      optionA: "'margin' adds space outside an element, while 'padding' adds space inside an element",
      optionB: "'padding' adds space outside an element, while 'margin' adds space inside an element",
      optionC: "'margin' and 'padding' both add space outside an element",
      optionD: "'margin' and 'padding' both add space inside an element",
      answer: "optionA",
    },
    {
      prompt: "What is a media query in CSS?",
      optionA: "A way to apply styles to elements based on their position in the HTML document",
      optionB: "A way to apply styles to elements only when they are hovered over",
      optionC: "A way to apply styles to elements only when they are clicked on",
      optionD: "A way to apply styles to elements based on the screen size or device orientation",
      answer: "optionD",
    },
    {
      prompt: "What is a callback function in JavaScript?",
      optionA: "A function that is called at the end of along-running operation",
      optionB: "A function that is called when an event occurs",
      optionC: "A function that is called when an error occurs",
      optionD: "A function that is called when a condition is met",
      answer: "optionB",
    },
    {
      prompt: "What is AJAX in JavaScript?",
      optionA: "A programming language used to create dynamic web pages",
      optionB: "A scripting language used to create dynamic web pages",
      optionC: "A technique used to send and receive data from a server asynchronously without reloading the page",
      optionD: "A method used to store and retrieve data in a database",
      answer: "optionC",
    },
    {
      prompt: "What is a RESTful API?",
      optionA: "A way to create dynamic web pages using JavaScript and CSS",
      optionB: "A way to store and retrieve data in a database",
      optionC: "A way to send and receive data from a server using the HTTP protocol",
      optionD: "A way to create and manipulate HTML documents using JavaScript",
      answer: "optionC",
    },
    {
      prompt: "What is a JSON?",
      optionA: "A programming language used to create dynamic web pages",
      optionB: "A scripting language used to create dynamic web pages",
      optionC: "A data format used to exchange data between a server and a client",
      optionD: "A database management system for storing and retrieving data",
      answer: "optionC",
    },
    {
      prompt: "What is a promise in JavaScript?",
      optionA: "A function that returns a value immediately",
      optionB: "A function that returns a value after a delay",
      optionC: "An object that represents the eventual completion or failure of an asynchronous operation",
      optionD: "A function that executes a set of statements based on a condition",
      answer: "optionC",
    },
    {
      prompt: "What is a closure in JavaScript?",
      optionA: "A way to create private variables and methods in an object",
      optionB: "A way to create a copy of an object",
      optionC: "A way to create a new object based on an existing one",
      optionD: "A function that has access to variables in its outer (enclosing) scope",
      answer: "optionD",
    },
    {
      prompt: "What is the difference between '==' and '===' in JavaScript?",
      optionA: "'==' compares values without considering their types, while '===' compares values and types",
      optionB: "'===' compares values without considering their types, while '==' compares values and types",
      optionC: "'==' and '===' both compare values and types",
      optionD: "'==' and '===' both compare values without considering their types",
      answer:"optionA",},
      {
        prompt: "What is the difference between 'let' and 'var' in JavaScript?",
        optionA: "'let' is block-scoped, while 'var' is function-scoped",
        optionB: "'var' is block-scoped, while 'let' is function-scoped",
        optionC: "'let' and 'var' are both block-scoped",
        optionD: "'let' and 'var' are both function-scoped",
        answer: "optionA",
      },
      {
        prompt: "What is the 'this' keyword in JavaScript?",
        optionA: "A keyword used to refer to the current function",
        optionB: "A keyword used to refer to the global object",
        optionC: "A keyword used to refer to the object that the function belongs to",
        optionD: "A keyword used to refer to the object that the function was called on",
        answer: "optionD",
      },
      {
        prompt: "What is a constructor function in JavaScript?",
        optionA: "A function used to create a new instance of an object",
        optionB: "A function used to add a new property to an object",
        optionC: "A function used to remove a property from an object",
        optionD: "A function used to modify an existing property of an object",
        answer: "optionA",
      },
      {
        prompt: "What is thedifference between 'slice' and 'splice' in JavaScript?",
        optionA: "'slice' returns a new array with a portion of the original array, while 'splice' modifies the original array by adding or removing elements",
        optionB: "'splice' returns a new array with a portion of the original array, while 'slice' modifies the original array by adding or removing elements",
        optionC: "'slice' and 'splice' both modify the original array by adding or removing elements",
        optionD: "'slice' and 'splice' both return a new array with a portion of the original array",
        answer: "optionA",
      },
      {
        prompt: "What is a try-catch block in JavaScript?",
        optionA: "A block of code used to handle errors that may occur in the code inside the try block",
        optionB: "A block of code used to try out different solutions to a problem",
        optionC: "A block of code used to test the performance of a function",
        optionD: "A block of code used to measure the memory usage of a program",
        answer: "optionA",
      },
      {
        prompt: "What is a module in JavaScript?",
        optionA: "A way to create reusable code that can be imported and used in other parts of a program",
        optionB: "A way to create new objects based on existing ones",
        optionC: "A way to createnew data types in JavaScript",
        optionD: "A way to create functions with default values for their parameters",
        answer: "optionA",
      },
      {
        prompt: "What is the difference between synchronous and asynchronous code in JavaScript?",
        optionA: "Synchronous code executes in a single thread and blocks other code from running, while asynchronous code allows other code to run while it is executing",
        optionB: "Asynchronous code executes in a single thread and blocks other code from running, while synchronous code allows other code to run while it is executing",
        optionC: "Synchronous code executes in multiple threads and blocks other code from running, while asynchronous code allows other code to run while it is executing",
        optionD: "Asynchronous code executes in multiple threads and blocks other code from running, while synchronous code allows other code to run while it is executing",
        answer: "optionA",
      },
      {
        prompt: "What is a callback function in Node.js?",
        optionA: "A function that is called at the end of a long-running operation",
        optionB: "A function that is called when an event occurs",
        optionC: "A function that is called when an error occurs",
        optionD: "A function that is called when a condition is met",
        answer: "optionB",
      },
      {
        prompt: "What is NPM in Node.js?",
        optionA: "A package managerused to install and manage packages/modules in a Node.js project",
        optionB: "A programming language used to create dynamic web pages",
        optionC: "A library used to create server-side applications in Node.js",
        optionD: "A database management system for storing and retrieving data in a Node.js project",
        answer: "optionA",
      },
      {
        prompt: "What is Express.js in Node.js?",
        optionA: "A package manager used to install and manage packages/modules in a Node.js project",
        optionB: "A programming language used to create dynamic web pages",
        optionC: "A library used to create server-side applications in Node.js",
        optionD: "A database management system for storing and retrieving data in a Node.js project",
        answer: "optionC",
      },
      {
        prompt: "What is MongoDB in Node.js?",
        optionA: "A package manager used to install and manage packages/modules in a Node.js project",
        optionB: "A programming language used to create dynamic web pages",
        optionC: "A library used to create server-side applications in Node.js",
        optionD: "A database management system for storing and retrieving data in a Node.js project",
        answer: "optionD",
      },
      {
        prompt: "What is the difference between a GET request and a POST request in HTTP?",
        optionA: "A GET request is used to retrieve data froma server, while a POST request is used to send data to a server to create or update a resource",
        optionB: "A GET request is used to send data to a server to create or update a resource, while a POST request is used to retrieve data from a server",
        optionC: "A GET request and a POST request are used interchangeably in HTTP",
        optionD: "A GET request and a POST request are used to retrieve data from a server",
        answer: "optionA",
      },
      {
        prompt: "What is the difference between HTTP and HTTPS?",
        optionA: "HTTP is a protocol used for secure communication over the internet, while HTTPS is a protocol used for unsecure communication over the internet",
        optionB: "HTTP is a protocol used for unsecure communication over the internet, while HTTPS is a protocol used for secure communication over the internet",
        optionC: "HTTP and HTTPS are two different names for the same protocol used for communication over the internet",
        optionD: "HTTP and HTTPS are two different protocols used for communication over different networks",
        answer: "optionB",
      },
      {
        prompt: "What is DNS?",
        optionA: "A protocol used for communication between servers and clients over the internet",
        optionB: "A database that stores information about domain names and their corresponding IP addresses",
        optionC: "A programming language used to create dynamic web pages",
        optionD: "A network protocol used for transferring files over the internet",
        answer: "optionB",
      },
      {
        prompt: "What is SSL/TLS?",
        optionA: "A protocol used for communication between servers and clients over the internet",
        optionB: "A database that stores information about domain names and their corresponding IP addresses",
        optionC: "A security protocol used to encrypt data sent over the internet",
        optionD: "A network protocol used for transferring files over the internet",
        answer: "optionC",
      },
      {
        prompt: "What is a firewall?",
        optionA: "A program that protects a computer from viruses and other malware",
        optionB: "A program that monitors and controls incoming and outgoing network traffic",
        optionC: "A program that encrypts data sent over the internet",
        optionD: "A program that detects and removes spyware from a computer",
        answer: "optionB",
      },
      {
        prompt: "What is a VPN?",
        optionA: "A protocol used for communication between servers and clients over the internet",
        optionB: "A database that stores information about domain names and their corresponding IP addresses",
        optionC: "A security protocol used to encrypt data sent over the internet",
        optionD: "A technology used to create a secure and private network connection over the internet",
        answer: "optionD",
      },
      {
        prompt: "What is a RESTful API?",
        optionA: "A type of API that uses SOAP as its communication protocol",
        optionB: "A type of API that uses URL endpoints to interact with resources using HTTP methods",
        optionC: "A type of API that uses binary encoding to send and receive data",
        optionD: "A type of API that is only used for internal communication within a single application",
        answer: "optionB",
      },
      {
        prompt: "What is the difference between PUT and PATCH HTTP methods?",
        optionA: "PUT is used to update an entire resource, while PATCH is used to update a partial resource",
        optionB: "PATCH is used to update an entire resource, while PUT is used to update a partial resource",
        optionC: "PUT and PATCH are interchangeable HTTP methods",
        optionD: "PUT and PATCH are both used to retrieve data from a server",
        answer: "optionA",
      },
      {
        prompt: "What is OAuth?",
        optionA: "A protocol used to secure communication between servers and clients over the internet",
        optionB: "A protocol used to authorize access to resources on a server without sharing the user's credentials",
        optionC: "A protocol used to encrypt data sent over the internet",
        optionD: "A protocol used to transfer files between servers and clients over the internet",
        answer: "optionB",
      },
      {
        prompt: "What is CORS in web development?",
        optionA: "A security mechanism that prevents web pages from making requests to a different domain than the one that served the web page",
        optionB: "A programming language used to create dynamic web pages",
        optionC: "A database that stores information about domain names and their corresponding IP addresses",
        optionD: "A protocol used to encrypt data sent over the internet",
        answer: "optionA",
      },
      {
        prompt: "What is AngularJS?",
        optionA: "A programming language used to create dynamic web pages",
        optionB: "A front-end web development framework",
        optionC: "A back-end web development framework",
        optionD: "A database management system for storing and retrieving data",
        answer: "optionB",
      },
      {
        prompt: "What is React?",
        optionA: "A programming language used to create dynamic web pages",
        optionB: "A front-end web development framework",
        optionC: "A back-end web development framework",
        optionD: "A database management system for storing and retrieving data",
        answer: "optionB",
      },
      {
        prompt: "What is Node.js?",
        optionA: "A front-end web development framework",
        optionB: "A back-end web development framework",
        optionC: "A database management system for storing and retrieving data",
        optionD: "A JavaScript runtime environment that executes JavaScript code outside of a web browser",
        answer: "optionD",
      },
      {
        prompt: "What is Docker?",
        optionA: "A containerization platform used to package and run applications in a portable way",
        optionB: "A database management system for storing and retrieving data",
        optionC: "A front-end web development framework",
        optionD: "A back-end web development framework",
        answer: "optionA",
      },
      {
        prompt: "What is Agile software development?",
        optionA: "A software development methodology that emphasizes comprehensive documentation and planning",
        optionB: "A software development methodology that emphasizes working software and collaboration between self-organizing cross-functional teams",
        optionC: "A software development methodology that emphasizes strict adherence to a predefined process",
        optionD: "A software development methodology that emphasizes strict control over the development process",
        answer: "optionB",
      },
      {
        prompt: "What is DevOps?",
        optionA: "A software development methodology that emphasizes comprehensive documentation and planning",
        optionB: "A software development methodology that emphasizes working software and collaboration between self-organizing cross-functional teams",
        optionC: "A software development methodology that emphasizes strict adherence to a predefined process",
        optionD: "A set of practices that combines software development and IT operations to shorten the systems development life cycle and provide continuous delivery with high software quality",
        answer: "optionD",
      },
      {
        prompt: "What is Git?",
        optionA: "A programming language used to create dynamic web pages",
        optionB: "A back-end web development framework",
        optionC: "A version control system used for software development",
        optionD: "A database management system for storing and retrieving data",
        answer: "optionC",
      },
      {
        prompt: "What is a pull request in Git?",
        optionA: "A request to merge changes from one branch into another",
        optionB: "A request to delete a branch in a Git repository",
        optionC: "A request to create a new branch in a Git repository",
        optionD: "A request to revert changes in a Git repository",
        answer: "optionA",
      },
      {
        prompt: "What is a merge conflict in Git?",
        optionA: "A conflict that occurs when two or more branches have changes that cannot be automatically merged by Git",
        optionB: "A conflict that occurs when a branch is deleted in a Git repository",
        optionC: "A conflict that occurs when a new branch is created in a Git repository",
        optionD:"A conflict that occurs when changes are reverted in a Git repository",
        answer: "optionA",
      },
      {
        prompt: "What is Continuous Integration (CI)?",
        optionA: "A software development practice where developers integrate their code changes frequently into a central repository, which is then verified by an automated build and test process",
        optionB: "A software development practice where developers work independently on their own code changes, which are then merged together after they are completed",
        optionC: "A software development practice where developers manually test their code changes before integrating them into a central repository",
        optionD: "A software development practice where developers only integrate their code changes at the end of a project",
        answer: "optionA",
      },
      {
        prompt: "What is Continuous Deployment (CD)?",
        optionA: "A software development practice where code changes are automatically deployed to production after passing through a series of automated tests",
        optionB: "A software development practice where code changes are manually deployed to production after passing through a series of manual tests",
        optionC: "A software development practice where code changes are only deployed to production at the end of a project",
        optionD: "A software development practice where code changes are not deployed to production until all developers have completed their work",
        answer: "optionA",
      },
      {
        prompt: "What is cloud computing?",
        optionA: "A type of computing where allthe processing and storage is done on a local computer or server",
        optionB: "A type of computing where processing and storage is done on remote servers accessed over the internet",
        optionC: "A type of computing where processing is done locally and storage is done on remote servers accessed over the internet",
        optionD: "A type of computing where processing is done on remote servers and storage is done locally on a local computer or server",
        answer: "optionB",
      },
      {
        prompt: "What is a virtual machine?",
        optionA: "A software program that emulates a physical computer system, allowing multiple operating systems to run on a single physical machine",
        optionB: "A type of computer that exists only in a virtual environment and does not have a physical counterpart",
        optionC: "A type of cloud service that provides virtualized computing resources over the internet",
        optionD: "A type of software that allows multiple users to access a single physical machine remotely",
        answer: "optionA",
      },
      {
        prompt: "What is a container?",
        optionA: "A type of virtual machine that runs a complete operating system and virtualizes all hardware resources",
        optionB: "A lightweight, standalone executable package that contains everything needed to run a piece of software, including the code, runtime, system tools, libraries, and settings",
        optionC: "A type of cloud service that provides virtualized computing resources overthe internet",
        optionD: "A type of software that allows multiple users to access a single physical machine remotely",
        answer: "optionB",
      },
      {
        prompt: "What is Kubernetes?",
        optionA: "A containerization platform used to package and run applications in a portable way",
        optionB: "A cloud computing platform that provides virtualized computing resources over the internet",
        optionC: "A front-end web development framework",
        optionD: "An open-source container orchestration system used to automate the deployment, scaling, and management of containerized applications",
        answer: "optionD",
      },
      {
        prompt: "What is a microservice?",
        optionA: "A small program that is part of a larger software system",
        optionB: "A type of virtual machine that runs a complete operating system and virtualizes all hardware resources",
        optionC: "A lightweight, standalone executable package that contains everything needed to run a piece of software, including the code, runtime, system tools, libraries, and settings",
        optionD: "A software architecture pattern where a large application is broken down into smaller, independent services that communicate with each other over a network",
        answer: "optionD",
      },
      {
        prompt: "What is REST?",
        optionA: "A programming language used to create dynamic web pages",
        optionB: "A back-end web development framework",
        optionC: "Aset of architectural principles for building web services",
        optionD: "A database management system for storing and retrieving data",
        answer: "optionC",
      },
      {
        prompt: "What is JSON?",
        optionA: "A programming language used to create dynamic web pages",
        optionB: "A back-end web development framework",
        optionC: "A database management system for storing and retrieving data",
        optionD: "A lightweight data interchange format that is easy for humans to read and write and easy for machines to parse and generate",
        answer: "optionD",
      },
      {
        prompt: "What is SQL?",
        optionA: "A programming language used to create dynamic web pages",
        optionB: "A back-end web development framework",
        optionC: "A database management system for storing and retrieving data",
        optionD: "A lightweight data interchange format that is easy for humans to read and write and easy for machines to parse and generate",
        answer: "optionC",
      },
      {
        prompt: "What is NoSQL?",
        optionA: "A programming language used to create dynamic web pages",
        optionB: "A back-end web development framework",
        optionC: "A database management system that uses a non-relational data model",
        optionD: "A lightweight data interchange format that is easy for humans to read and write and easy for machines to parse and generate",
        answer: "optionC",
      },
      {
        prompt: "What is a cache?",
        optionA: "A type of memory used to store frequently accessed data for faster access",
        optionB: "A type of storage device used to store large amounts of data for long-term retention",
        optionC: "A type of network protocol used for transferring files between servers and clients over the internet",
        optionD: "A type of security mechanism used to prevent unauthorized access to a network or computer system",
        answer: "optionA",
      },
      {
        prompt: "What is a CDN?",
        optionA: "A type of storage device used to store large amounts of data for long-term retention",
        optionB: "A type of network protocol used for transferring files between servers and clients over the internet",
        optionC: "A type of security mechanism used to prevent unauthorized access to a network or computer system",
        optionD: "A network of servers distributed around the world that deliver web content to users based on their geographic location",
        answer: "optionD",
      },
      {
        prompt: "What is SSL?",
        optionA: "A type of storage device used to store large amounts of data forlong-term retention",
        optionB: "A network protocol used for transferring files between servers and clients over the internet",
        optionC: "A security mechanism used to prevent unauthorized access to a network or computer system",
        optionD: "A protocol used to encrypt data sent over the internet",
        answer: "optionD",
      },
      {
        prompt: "What is OAuth?",
        optionA: "A security mechanism used to prevent unauthorized access to a network or computer system",
        optionB: "A protocol used to transfer files between servers and clients over the internet",
        optionC: "A protocol used to encrypt data sent over the internet",
        optionD: "An authentication protocol used to allow users to grant third-party access to their resources without sharing their credentials",
        answer: "optionD",
      },
      {
        prompt: "What is a RESTful API?",
        optionA: "An API that uses a relational database to store and retrieve data",
        optionB: "An API that uses a non-relational database to store and retrieve data",
        optionC: "An API that follows the principles of REST, a set of architectural principles for building web services",
        optionD: "An API that uses XML as its data format",
        answer: "optionC",
      },
      {
        prompt: "What is a serverless architecture?",
        optionA: "An architecture where all the processing and storage is done on a local computer orserver",
        optionB: "An architecture where processing and storage is done on remote servers accessed over the internet",
        optionC: "An architecture where processing is done locally and storage is done on remote servers accessed over the internet",
        optionD: "An architecture where the infrastructure, scaling, and management of servers is abstracted away from developers, allowing them to focus on writing code",
        answer: "optionD",
      },
      {
        prompt: "What is a code repository?",
        optionA: "A place where source code is stored and managed",
        optionB: "A place where executable code is stored and managed",
        optionC: "A place where data is stored and managed",
        optionD: "A place where documentation is stored and managed",
        answer: "optionA",
      },
      {
        prompt: "What is a code review?",
        optionA: "A process of testing code to ensure it meets the specified requirements",
        optionB: "A process of reviewing code to ensure it is well-written, maintainable, and adheres to best practices",
        optionC: "A process of debugging code to fix errors and issues",
        optionD: "A process of documenting code to ensure it is understandable and usable by others",
        answer: "optionB",
      },
      {
        prompt: "What is pair programming?",
        optionA: "A programming technique where two developers work together on the same codebase, takingturns writing code and reviewing each other's work",
        optionB: "A programming technique where one developer writes code while the other reviews and provides feedback",
        optionC: "A programming technique where one developer writes code while the other tests it",
        optionD: "A programming technique where developers work independently on their own code changes, which are then merged together after they are completed",
        answer: "optionA",
      },
      {
        prompt: "What is a software bug?",
        optionA: "An issue in software that causes it to crash or malfunction",
        optionB: "A security vulnerability in software that can be exploited by attackers",
        optionC: "A feature in software that is not working as intended",
        optionD: "A programming language construct that is not valid syntax",
        answer: "optionA",
      },
      {
        prompt: "What is a software patch?",
        optionA: "A type of software bug that is particularly difficult to fix",
        optionB: "A small piece of code that is used to fix a specific issue in software",
        optionC: "A type of software that is used to scan for and remove viruses and malware",
        optionD: "A type of software that is used to track and manage bugs in a software project",
        answer: "optionB",
      },
      {
        prompt: "What is refactoring?",
        optionA: "A process of writing code that is optimizedfor performance",
        optionB: "A process of making changes to code to improve its structure, readability, and maintainability without changing its external behavior",
        optionC: "A process of testing code to ensure it meets the specified requirements",
        optionD: "A process of debugging code to fix errors and issues",
        answer: "optionB",
      },
      {
        prompt: "What is continuous integration?",
        optionA: "A process of continuously testing code to ensure it meets the specified requirements",
        optionB: "A process of continuously deploying code to production",
        optionC: "A process of continuously monitoring code to detect and fix errors and issues",
        optionD: "A process of continuously integrating code changes from multiple developers into a single codebase and ensuring that the codebase is always in a working state",
        answer: "optionD",
      },
      {
        prompt: "What is continuous deployment?",
        optionA: "A process of continuously testing code to ensure it meets the specified requirements",
        optionB: "A process of continuously deploying code to production",
        optionC: "A process of continuously monitoring code to detect and fix errors and issues",
        optionD: "A process of continuously integrating code changes from multiple developers into a single codebase and ensuring that the codebase is always in a working state",
        answer: "optionB",
      },
      {
        prompt: "What is DevOps?",
        optionA: "A software development methodology that emphasizes collaboration and communication between developers and operations teams",
        optionB: "A programming language used for web development",
        optionC: "A type of software that is used to manage databases",
        optionD: "A type of security mechanism used to prevent unauthorized access to a network or computer system",
        answer: "optionA",
      },
      {
        prompt: "What is agile software development?",
        optionA: "A software development methodology that emphasizes thorough planning and documentation before any code is written",
        optionB: "A software development methodology that emphasizes rapid iteration, continuous feedback, and flexibility in the face of changing requirements",
        optionC: "A software development methodology that emphasizes strict adherence to a set of standardized processes and procedures",
        optionD: "A software development methodology that emphasizes individual coding skills and expertise over teamwork and collaboration",
        answer: "optionB",
      },
      {
        prompt: "What is version control?",
        optionA: "A process of testing code to ensure it meets the specified requirements",
        optionB: "A process of documenting code to ensure it is understandable and usable by others",
        optionC: "A process of managing changes to code over time, allowing developers to track changes, collaborate on code, and revert to earlier versions if necessary",
        optionD: "A process of optimizing code for performance",
        answer: "optionC",
      },
      {
        prompt: "What is a programminglanguage?",
        optionA: "A set of instructions for a computer to execute",
        optionB: "A set of tools for developing software",
        optionC: "A set of rules for formatting code",
        optionD: "A set of guidelines for testing software",
        answer: "optionA",
      },
      {
        prompt: "What is a compiler?",
        optionA: "A type of software that is used to manage databases",
        optionB: "A type of software that is used to create graphical user interfaces",
        optionC: "A type of software that is used to encrypt data sent over the internet",
        optionD: "A type of software that translates source code written in a programming language into machine code that can be executed by a computer",
        answer: "optionD",
      },
      {
        prompt: "What is an IDE?",
        optionA: "A type of software that is used to manage databases",
        optionB: "A type of software that is used to create graphical user interfaces",
        optionC: "A type of software that is used to encrypt data sent over the internet",
        optionD: "An integrated development environment, which is a type ofsoftware that provides a comprehensive environment for software development, including a text editor, a debugger, and tools for building, testing, and deploying software",
        answer: "optionD",
      },
      {
        prompt: "What is a library?",
        optionA: "A collection of pre-written code that can be used to perform common tasks",
        optionB: "A collection of documentation for a programming language or software project",
        optionC: "A collection of tools for developing software",
        optionD: "A collection of test cases for a software project",
        answer: "optionA",
      },
      {
        prompt: "What is a framework?",
        optionA: "A type of software that is used to manage databases",
        optionB: "A collection of tools for developing software",
        optionC: "A set of rules for formatting code",
        optionD: "A set of guidelines for testing software",
        answer: "optionB",
      },
      {
        prompt: "What is a package manager?",
        optionA: "A type of software that is used to manage databases",
        optionB: "A type of software that is used to create graphical user interfaces",
        optionC: "A type of software that is used to manage the installation, update, and removal of software packages",
        optionD: "A type of software that is used to encrypt data sent over the internet",
        answer: "optionC",
      },
      {
    prompt: "What is a container?",
        optionA: "A type of storage device used to store large amounts of data for long-term retention",
        optionB: "A type of virtual machine that allows multiple operating systems to run on a single physical machine",
        optionC: "A lightweight, standalone executable package that contains everything needed to run a piece of software, including code, libraries, and dependencies",
        optionD: "A type of network protocol used for transferring files between servers and clients over the internet",
        answer: "optionC",
      },
      {
        prompt: "What is machine learning?",
        optionA: "A type of software development methodology that emphasizes rapid iteration, continuous feedback, and flexibility in the face of changing requirements",
        optionB: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionC: "A type of security mechanism used to prevent unauthorized access to a network or computer system",
        optionD: "A type of software that is used to manage databases",
        answer: "optionB",
      },
      {
        prompt: "What is deep learning?",
        optionA: "A type of machine learning that involves training artificial neural networks to recognize patterns in data",
        optionB: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionC: "A type of database management system that uses a non-relational data model",
        optionD: "A type of software that is used to manage the installation, update, and removal of software packages",
        answer: "optionA",
      },
      {
        prompt: "What is natural language processing?",
        optionA: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionB: "A type of machine learning that involves training artificial neural networks to recognize patterns in data",
        optionC: "A type of software that is used to manage databases",
        optionD: "A field of study that focuses on the interaction between computers and human languages, including tasks such as language translation and sentiment analysis",
        answer: "optionD",
      },
      {
        prompt: "What is computer vision?",
        optionA: "A type of machine learning that involves training artificial neural networks to recognize patterns in data",
        optionB: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionC: "A type of software that is used to manage databases",
        optionD: "A field of study that focuses on enabling computers to interpret and understand visual information from the world",
        answer: "optionD",
      },
      {
        prompt: "What is artificial intelligence?",
        optionA: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
       optionB: "A type of machine learning that involves training artificial neural networks to recognize patterns in data",
        optionC: "A type of software that is used to manage databases",
        optionD: "A field of study that focuses on creating intelligent machines that can perform tasks that typically require human intelligence, such as visual perception, speech recognition, and decision-making",
        answer: "optionD",
      },
      {
        prompt: "What is blockchain?",
        optionA: "A type of database management system that uses a non-relational data model",
        optionB: "A type of software that is used to manage the installation, update, and removal of software packages",
        optionC: "A type of network protocol used for transferring files between servers and clients over the internet",
        optionD: "A distributed ledger technology that enables secure, transparent, and tamper-proof record-keeping of transactions and data",
        answer: "optionD",
      },
      {
        prompt: "What is cryptocurrency?",
        optionA: "A type of distributed ledger technology that enables secure, transparent, and tamper-proof record-keeping of transactions and data",
        optionB: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionC: "A type of software that is used to manage databases",
        optionD: "A digital or virtual currency that uses cryptography for security and operates independently of a central bank",
        answer: "optionD",
      },
      {
        prompt: "What is cloud computing?",
        optionA: "A type of software that is used to manage databases",
        optionB: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionC: "A type of distributed computing that involves connecting computers together to form a single, powerful system",
        optionD: "A type of computing that involves delivering computing services over the internet, including servers, storage, databases, and software",
        answer: "optionD",
      },
      {
        prompt: "What is the internet of things (IoT)?",
        optionA: "A type of distributed computing that involves connecting computers together to form a single, powerful system",
        optionB: "A type of computing that involves delivering computing services over the internet, including servers, storage, databases, and software",
        optionC: "A network of physical devices, vehicles, home appliances, and other items embedded with electronics, software, sensors, and connectivity, which enables these objects to connect and exchange data",
        optionD: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        answer: "optionC",
      },
      {
        prompt: "What is big data?",
        optionA: "A type of computing that involves delivering computing services over the internet, including servers, storage, databases, and software",
        optionB: "A term used to describe datasets that are too large and complex for traditional data processing and analysis tools",
        optionC: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionD: "A type of network protocol used for transferring files between servers and clients over the internet",
        answer: "optionB",
      },
      {
        prompt: "What is data science?",
        optionA: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionB: "A field of study that combines statistical analysis, computer science, and domain expertise to extract insights from data",
        optionC: "A type of software that is used to manage databases",
        optionD: "A type of machine learning that involves training artificial neural networks to recognize patterns in data",
        answer: "optionB",
      },
      {
        prompt: "What is agile methodology?",
        optionA: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionB: "A type of software that is used to manage databases",
        optionC: "A type of software development methodology that emphasizes rapid iteration, continuous feedback, and flexibility in the face of changing requirements",
        optionD: "A type of security mechanism used to prevent unauthorized access to a network or computer system",
       answer: "optionC",
      },
      {
        prompt: "What is DevOps?",
        optionA: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionB: "A type of software that is used to manage databases",
        optionC: "A type of software development methodology that emphasizes collaboration and communication between development and operations teams to enable faster and more reliable software delivery",
        optionD: "A type of security mechanism used to prevent unauthorized access to a network or computer system",
        answer: "optionC",
      },
      {
        prompt: "What is cybersecurity?",
        optionA: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionB: "A field of study that focuses on the protection of computer systems and networks from theft, damage, or unauthorized access",
        optionC: "A type of software that is used to manage databases",
        optionD: "A type of machine learning that involves training artificial neural networks to recognize patterns in data",
        answer: "optionB",
      },
      {
        prompt: "What is encryption?",
        optionA: "The process of converting information into a code to prevent unauthorized access or modification",
        optionB: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionC: "A type of software that is used to manage databases",
        optionD: "A type of network protocol used for transferring files between servers and clients over the internet",
        answer: "optionA",
      },
      {
        prompt: "What is a virtual machine?",
        optionA: "A type of software that is used to manage the installation, update, and removal of software packages",
        optionB: "A type of computer program that runs on a physical machine and emulates a separate computer system within it",
        optionC: "A type of database management system that uses a non-relational data model",
        optionD: "A type of network protocol used for transferring files between servers and clients over the internet",
        answer: "optionB",
      },
      {
        prompt: "What is a server?",
        optionA: "A type of computer program that runs on a physical machine and emulates a separate computer system within it",
        optionB: "A type of software that is used to manage the installation, update, and removal of software packages",
        optionC: "A type of computer that is designed to provide services or resources to other computers on a network",
        optionD: "A collection of pre-written code thatcan be used to perform common tasks",
        answer: "optionC",
      },
      {
        prompt: "What is a client-server model?",
        optionA: "A type of software development methodology that emphasizes rapid iteration, continuous feedback, and flexibility in the face of changing requirements",
        optionB: "A type of network topology that connects devices in a linear chain",
        optionC: "A type of computing architecture where a central server provides resources or services to multiple client devices",
        optionD: "A type of security mechanism used to prevent unauthorized access to a network or computer system",
        answer: "optionC",
      },
      {
        prompt: "What is a protocol?",
        optionA: "A type of software that is used to manage databases",
        optionB: "A set of rules or standards that govern the exchange of data between devices or systems",
        optionC: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionD: "A type of distributed computing that involves connecting computers together to form a single, powerful system",
        answer: "optionB",
      },
      {
        prompt: "What is an API?",
        optionA: "A type of software that is used to manage databases",
        optionB: "A set of rules or standards that govern the exchange of data between devices or systems",
        optionC: "A type of programming that involves teaching computers torecognize patterns in data and make decisions based on those patterns",
        optionD: "A set of pre-defined functions or protocols for building software applications",
        answer: "optionD",
      },
      {
        prompt: "What is version control?",
        optionA: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionB: "A type of software that is used to manage databases",
        optionC: "The process of tracking and managing changes to code or other files over time",
        optionD: "A type of network protocol used for transferring files between servers and clients over the internet",
        answer: "optionC",
      },
      {
        prompt: "What is continuous integration?",
        optionA: "The process of tracking and managing changes to code or other files over time",
        optionB: "A type of software that is used to manage databases",
        optionC: "A type of software development methodology that emphasizes collaboration and communication between development and operations teams to enable faster and more reliable software delivery",
        optionD: "The process of automatically building and testing code changes as they are made, to ensure that the software remains functional and stable",
        answer: "optionD",
      },
      {
        prompt: "What is continuous delivery?",
        optionA: "The process of automatically building and testing code changes as they are made, to ensure that the software remains functional and stable",
       optionB: "A type of software that is used to manage databases",
        optionC: "A type of software development methodology that emphasizes collaboration and communication between development and operations teams to enable faster and more reliable software delivery",
        optionD: "The process of tracking and managing changes to code or other files over time",
        answer: "optionA",
      },
      {
        prompt: "What is continuous deployment?",
        optionA: "The process of automatically building and testing code changes as they are made, to ensure that the software remains functional and stable",
        optionB: "A type of software that is used to manage databases",
        optionC: "A type of software development methodology that emphasizes collaboration and communication between development and operations teams to enable faster and more reliable software delivery",
        optionD: "The process of automatically deploying code changes to production environments as soon as they are ready",
        answer: "optionD",
      },
      {
        prompt: "What is scalability?",
        optionA: "The ability of a system or application to handle a growing amount of work or users without sacrificing performance or reliability",
        optionB: "A type of programming that involves teaching computers to recognize patterns in data and make decisions based on those patterns",
        optionC: "A type of software that is used to manage databases",
        optionD: "A type of network protocol used for transferring files between servers and clients over the internet",
        answer: "optionA",
     }]
    
